-- AlterTable
ALTER TABLE "BlogPost" ADD COLUMN     "author" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "preview" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "publishedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
