-- AlterEnum
ALTER TYPE "FeatureFlagKey" ADD VALUE 'MEMBERSHIP_TERMINATION';
ALTER TYPE "FeatureFlagKey" ADD VALUE 'MEMBERSHIP_TERMINATION_MAIL';
ALTER TYPE "FeatureFlagKey" ADD VALUE 'MEMBERSHIP_TERMINATION_CONFIRMATION_MAIL';
ALTER TYPE "FeatureFlagKey" ADD VALUE 'ACCOUNT_NOTICE_MAIL';
